# Generated by Django 2.2.4 on 2019-09-06 10:41

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', djongo.models.fields.ListField()),
                ('data', djongo.models.fields.ListField()),
                ('team_name', models.CharField(max_length=200)),
            ],
        ),
    ]
