# Generated by Django 2.2.4 on 2019-09-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
